"""
Helper functions pulled from stitches that are helpful!
"""

import fsspec
import intake
import xarray as xr
from tqdm import tqdm
import numpy as np
import pandas as pd
import re
import os

def download_ncs(row, write_dir):
    """
    Download the netcdf files from Pangeo and write them to a local directory.

    :param row: A pandas Series containing the information for a single CMIP6 data file.
    :param write_dir: The directory where the downloaded netcdf files will be saved.
    :type row: pandas.Series
    :type write_dir: str
    """
    data_path = row["zstore"]
    var_name = row["variable"]
    
    # Determine the tag name for the output file
    tag = data_path.replace("gs://", "").replace("/", "_").replace("cmip6_CMIP6_CMIP_", "").replace("cmip6_CMIP6_ScenarioMIP_", "")
    
    # Define the output file path
    output_file = os.path.join(write_dir, f"{tag}_{var_name}.nc")
    
    # Fetch the netcdf file from Pangeo
    ds = fetch_nc(data_path)
    
    # Save the dataset to a netcdf file
    ds.to_netcdf(output_file, mode='w')

    #fetch_nc(row["areacella"]).to_netcdf(os.path.join(write_dir, f"{tag}_{var_name}_cellarea.nc"),
    #                                      mode = 'w')
    #fetch_nc(row["sftlf"]).to_netcdf(os.path.join(write_dir, f"{tag}_{var_name}_landpct.nc"),
    #                                          mode = 'w')



def load_and_prep_netcdf(row, DATA_DIR):

    to_process = row.copy() 

    data_path = to_process["zstore"]
    
    
    # Determine the tag name, this is how
    tag = data_path.replace("gs://", "")
    tag = tag.replace("/", "_")
    tag = tag.replace("cmip6_CMIP6_CMIP_", "")
    tag = tag.replace("cmip6_CMIP6_ScenarioMIP_", "")
    
    
    # Files that are going to be generated by this script...
    field_ofile = DATA_DIR + "field/" + tag + "field.nc"
    global_ofile = DATA_DIR + "global/" + tag + "global.nc"
    
    d = fetch_nc(data_path)
    cell_area = fetch_nc(to_process["areacella"])
    land_percent = fetch_nc(to_process["sftlf"])
    
    # Save meta data information
    VAR = d.variable_id
    all_attrs = d.attrs
    original_units = d[VAR].units
    keys_to_keep = ["variable_id", "variant_label", "experiment_id", "frequency", "grid_label", "source_id"]
    meta_data = {k: all_attrs[k] for k in keys_to_keep if k in all_attrs}

    if VAR == "tas":
        # The first thing to do is to get the gridded annual mean that will be
        # used in the linear process scaling. Will need to update the frequency.
        # Save a copy of the annual mean values to local disk, this will be used in LPS.
        annual_field = d.coarsen(time=12).mean() - 273.15
    
        # Let's work on in the temperature anomoly space...
        selected_data = annual_field.sel(time=slice('1850', '1900'))
        ref_temp = selected_data.mean(dim="time")
        field = annual_field - ref_temp
        field.attrs["frequency"] = 'yr'
        field.to_netcdf(field_ofile, mode='w')
    
        # Now get the global mean value, these global values need to be weighted.
        lat = field[fetch_nc.get_lat_name(field)]
        weight = np.cos(np.deg2rad(lat))
        weight /= weight.mean()
        other_dims = set(d.dims) - {"time"}
        global_ts = (field * weight).mean(other_dims)
        global_ts.to_netcdf(global_ofile, mode='w')
    elif VAR in ["npp", "rh"]:
    
        # The first thing we need to do is get the annual field which should be total
        # carbon content per year.
        # TODO right now we are assuming a 365 day calander across models we may want to update this.
        seconds_per_year = (365 * 24 * 60 * 60) / 12
        annual_monthly_rate = d.coarsen(time=12).sum() * seconds_per_year
    
        # Calculate the land cell area, make sure that the land cell area where
        # land is 0 assign it a na value so that
        land_cell_area = cell_area.areacella * land_percent.sftlf * (1 / 100)
        land_cell_area = land_cell_area.where(land_cell_area != 0, other=np.nan)
    
        # Calculate the total annual carbon. Update attributes to reflect the
        # new units.
        # TODO figure out a way to add the attribtue information!
        field = annual_monthly_rate * land_cell_area.values
        #np.nanmax(field.npp.values)
    
        # Convert from kg of C to the Petagram of C which are the
        # unites I am used to thinking in/hector units.
        field = field * 1e-12
        #np.nanmax(field.npp.values)
    
        # annual_total_carbon = annual_total_carbon.assign_attrs()
        # meta_data["frequency"] = "yr"
        # meta_data["units"] = original_units.replace(" m-2 s-1", "")
        # for k, v in meta_data.items():
        #    annual_total_carbon.attrs[f"{k}"] = str(v)
        field.attrs["frequency"] = "year"
        field.attrs["units"] = "Pg C"
        field.to_netcdf(field_ofile, mode="w")
    
        # The global values, for the carbon values this is going to be
        # the global total, since we have already multiplied by the
        # land area we do not need to do the weighting.
        other_dims = set(field.dims) - {"time"}
        global_ts = field.sum(other_dims, skipna=True)
        global_ts.to_netcdf(global_ofile, mode='w')

        # The times should align since we are originating from the same raw netcdf file
        # although this is an assumption TODO don't rely on assumptions.
        field_with_global = field.copy()
        field_with_global["time"] = global_ts[VAR]
        field_with_global = field_with_global.rename({VAR: "field"})
    
    else:
        print("Data processing not implemented")

        

    return([field, global_ts, field_with_global])

    # end load_and_prep_netcdf

def get_yhat(beta, intercept, global_ts):

    VAR = list(global_ts.data_vars)
    yhat = beta.field_polyfit_coefficients * global_ts[VAR]+ intercept.field_polyfit_coefficients
    yhat = yhat.transpose(*("lat", "lon", "time"))
    # debugging
    #yhat.min(skipna=True)
    #yhat.max(skipna=True)
    #yhat.mean(skipna=True)

    return yhat

def get_errs(yhat, field):
    var_obs = field.var(dim="time")
    sd_obs = var_obs ** 0.5
    sd_sim = yhat.var(dim="time") ** 0.5
    mean_obs = field.mean(dim="time")
    mean_sim = yhat.mean(dim="time")

    resid = yhat - field
    mse = (resid * resid).mean(dim="time")
    ns = mse / var_obs
    ct_bias = abs(mean_obs - mean_sim) / sd_obs
    ct_var = sd_sim / sd_obs

    return resid, mse, ns, ct_bias, ct_var

def extrat_exp_ens(file_path:str):
    # Extract the basename
    base_name = os.path.basename(file_path)

    # Extract the experiment name
    if "historical" in base_name:
        exp_name = "historical"
    elif "ssp585" in base_name:
        exp_name = "ssp585"
    else:
        raise Exception("Something went wrong.")

    # Extract the ensemble member name
    match = re.search(r"r\d+i\d+p\d+f\d+", base_name)
    ens_name = match.group()

    out = pd.DataFrame({"experiment": [exp_name], "ensemble": [ens_name]})
    return out


def fetch_nc(zstore: str):
    """
    Extract data for a single file from Pangeo.

    :param zstore: The location of the CMIP6 data file on Pangeo.
    :type zstore: str
    :return: An xarray Dataset containing CMIP6 data downloaded from Pangeo.
    """
    print(f"Fetching: {zstore}")

    # Function to update the progress bar
    def update_progress_bar(mapper, bar):
        keys = list(mapper.keys())

        for key in keys:
            _ = mapper[key]  # Trigger the actual read
            bar.update(1)

    # Create a file system mapper
    mapper = fsspec.get_mapper(zstore)

    # Initialize the progress bar
    with tqdm(total=len(mapper.keys()), desc="Downloading file components: ") as bar:
        update_progress_bar(mapper, bar)

    # Open the dataset
    ds = xr.open_zarr(mapper)

    if hasattr(ds, "time"):
        ds.sortby("time")

    return ds


def get_xr_meta(ds):
    """
    Get the metadata information from an xarray dataset.

    :param ds: xarray dataset of CMIP data.
    :return: pandas DataFrame of MIP information.
    """
    v = ds.variable_id

    data = [
        {
            "variable": v,
            "experiment": ds.experiment_id,
            "units": ds[v].attrs["units"],
            "frequency": ds.attrs["frequency"],
            "ensemble": ds.attrs["variant_label"],
            "model": ds.source_id,
        }
    ]
    df = pd.DataFrame(data)

    return df


def get_lat_name(ds):
    """Get the name for the latitude values in an xarray dataset.

    This function searches for latitude coordinates in the dataset,
    which could be named either 'lat' or 'latitude'.

    :param ds: The dataset from which to retrieve the latitude coordinate name.
    :type ds: xarray.Dataset
    :returns: The name of the latitude variable.
    :rtype: str
    :raises RuntimeError: If no latitude coordinate is found in the dataset.
    """
    for lat_name in ["lat", "latitude"]:
        if lat_name in ds.coords:
            return lat_name
    raise RuntimeError("Couldn't find a latitude coordinate")






def global_total(ds):
    """
    Calculate the weighted global total for a variable in an xarray dataset.

    :param ds: The xarray dataset of CMIP data.
    :type ds: xarray.Dataset
    :returns: The xarray dataset of the weighted global mean.
    :rtype: xarray.Dataset
    """
    lat = ds[get_lat_name(ds)]
    weight = np.cos(np.deg2rad(lat))
    weight /= weight.mean()
    other_dims = set(ds.dims) - {"time"}
    return (ds * weight).mean(other_dims)



def selstr(a, start, stop):
    """
    Select elements of a string from start to stop index.

    :param a: Array containing a string.
    :type a: str
    :param start: First character index to select.
    :type start: int
    :param stop: Last character index to select.
    :type stop: int
    :returns: Array of strings.
    :rtype: list
    """
    if type(a) not in [str]:
        raise TypeError("a: must be a single string")

    out = []
    for i in range(start, stop):
        out.append(a[i])
    out = "".join(out)
    return out

def get_lat_name(ds):
    """Get the name for the latitude values in an xarray dataset.

    This function searches for latitude coordinates in the dataset,
    which could be named either 'lat' or 'latitude'.

    :param ds: The dataset from which to retrieve the latitude coordinate name.
    :type ds: xarray.Dataset
    :returns: The name of the latitude variable.
    :rtype: str
    :raises RuntimeError: If no latitude coordinate is found in the dataset.
    """
    for lat_name in ["lat", "latitude"]:
        if lat_name in ds.coords:
            return lat_name
    raise RuntimeError("Couldn't find a latitude coordinate")


def subset_join(df1, df2):
    """
    Join two pandas data frames into a single data frame and subset the df1

    :param df1: First pandas DataFrame.
    :param df2: Second pandas DataFrame.
    :return: A single pandas DataFrame resulting from the joining of df1 and df2.
    """

    incommon = df1.columns.intersection(df2.columns).tolist()
    if len(incommon) == 0:
        raise TypeError("a: df1 and df2 must have names in common.")

    rows_df1 = df1.shape[0]
    rows_df2 = df2.shape[0]

    if (rows_df1 > rows_df2):
        raise TypeError("b: df1 needs to be the more restrictive data frame.")

    df1["to_keep"] = 1
    subset_df = df1.merge(df2, on=incommon, how="inner")
    subset_df = subset_df[subset_df["to_keep"] == 1]
    out = subset_df.drop('to_keep', axis=1)

    return out


def combine_df(df1, df2):
    """
    Join two pandas data frames into a single data frame.

    :param df1: First pandas DataFrame.
    :param df2: Second pandas DataFrame.
    :return: A single pandas DataFrame resulting from the joining of df1 and df2.
    """
    incommon = df1.columns.intersection(df2.columns)
    if len(incommon) > 0:
        raise TypeError("a: df1 and df2 must have unique column names.")

    # Combine the two data frames with one another.
    df1["j"] = 1
    df2["j"] = 1
    out = df1.merge(df2)
    out = out.drop(columns="j")

    return out


