# This script is meant to figure out how to do the mapping from a raw netcdf file to the GCAM land use regions...

# Set Up -----------------------------------------------------------------------
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
import os
import fxns
from scipy.interpolate import griddata
import geopandas as gpd


OUT_DIR = "./dev/"

# Helper function -------------------------------------------------------------------
# TODO need to document!
def to_0360(lon):
    return (lon % 360)

def to_m180_180(lon):
    return ((lon + 180) % 360) - 180


# Load CMIP6  -----------------------------------------------------------------------
# Read in the data frame with the files to process
to_process = pd.read_csv('./npp_rh_to_process.csv')
index = 0

data_path = to_process["zstore"][index]
# Load the required netcdf files.
d = fxns.fetch_nc(data_path)
d = d.drop_dims("bnds")
# Prep the GCAM Map ----------------------------------------------------------------

# Read in the GCAM grid region basin file generated by hte 0.get_GLU_map.R script which
# extracts this information from the gaia pacakge.
df = pd.read_csv("GCAM_grid_region_basin.csv")

# Since the GCAM grid is a csv file of lat & lon coordinated we are going to want to
# construct an xarray that is comptible with the CMIP6 netcdf files.

# Sort and pivot to 2D (lat x lon)
lat_vals = np.sort(df['lat'].unique())
lon_vals = np.sort(df['lon'].unique())


# Shape from lat and lon into a Xarray
GLU_mask = (
    df.set_index(['lat', 'lon'])['glu_id']
      .to_xarray()                              # DataArray with dims ('lat','lon')
      .sortby('lat').sortby('lon')
)

#GLU_mask.plot()             # xarray picks sensible defaults
#plt.show()


# Since the only CMIP6 data we are working with is with
# lon is 0..360 and mask is -180..180, convert mask to 0..360 (or vice versa)
# TODO may need to change if working with other CMIP6 or other sources
# of information
GLU_mask = GLU_mask.assign_coords(lon=to_0360(GLU_mask['lon']))

# Sort after coordinate change
GLU_mask = GLU_mask.sortby('lon')
GLU_mask_cmip6 = GLU_mask.interp(lat=d.lat, lon=d.lon, method="nearest")
# Replace the lat/lon that do not coordinate with a GLU with na to -1,
# this might be a work around for the RuntimeWarning encountered with the groupby call.
#GLU_mask_cmip6=GLU_mask_cmip6.fillna(-1).astype("int32")

# Check to make sure we've got the same dim & values for the
# lat and lon! If any of these are false or non 0 then we
# have a problem
#GLU_mask_cmip6.lat.values.shape == d.lat.values.shape
#GLU_mask_cmip6.lat.values - d.lat.values
#GLU_mask_cmip6.lon.values.shape == d.lon.values.shape
#GLU_mask_cmip6.lon.values - d.lon.values
print((d.lat == GLU_mask_cmip6.lat).all())
print((d.lon == GLU_mask_cmip6.lon).all())

# TODO
# this might return a RuntimeWarning but it is unclear what is causing it and
# can ba ignored
glu_total_xr = d.groupby(GLU_mask_cmip6).sum(dim=["stacked_lat_lon"])

# Okay so I think that in order to do the plotting we will need to do the reverse
# of what was done to create the mask in the first place.
LON, LAT = np.meshgrid(lon_vals, lat_vals)

# STUCK HERE
Zgrid = griddata(
    points=np.column_stack([df.lon, df.lat]),
    values=df.glu_id,
    xi=np.column_stack([LON.ravel(), LAT.ravel()]),
    method='nearest'   # also try 'linear' (needs more points), 'cubic'
).reshape(LAT.shape)


# 5) Wrap into xarray for plotting
grid = xr.DataArray(
    Zgrid,
    coords={'lat': lat_vals, 'lon': lon_vals},
    dims=('lat','lon'),
    name=glu_total_xr.npp.values
)




xx = glu_total_xr.values
np.percentile(xx, 1)
xx.min()




# okay so I think that these are the right values, the issue then though is how to
# map from the aggreagted by





mapped_grid = xr.where(GLU_mask_cmip6 >= 0, glu_total.sel(region=glu_id), np.nan)


GLU_mask_cmip6.to_series().unique()
GLU_mask_cmip6.isnull().sum()
GLU_mask_cmip6.dtype
xr.align(d, GLU_mask_cmip6)
d.bnds
GLU_mask_cmip6.to_series().unique()
country_mean.plot()             # xarray picks sensible defaults
plt.show()

# Main Chunk -----------------------------------------------------------------------
# Read in the data frame with the files to process
to_process = pd.read_csv('./npp_rh_to_process.csv')
index = 0

data_path = to_process["zstore"][index]

# Determine the tag name, this is how
tag = data_path.replace("gs://", "")
tag = tag.replace("/", "_")
tag = tag.replace("cmip6_CMIP6_CMIP_", "")
tag = tag.replace("cmip6_CMIP6_ScenarioMIP_", "")

# Load the required netcdf files.
d = fxns.fetch_nc(data_path)
cell_area = fxns.fetch_nc(to_process["areacella"][index])
land_percent = fxns.fetch_nc(to_process["sftlf"][index])

# Save meta data information
VAR = d.variable_id
all_attrs = d.attrs
original_units = d[VAR].units
keys_to_keep = ["variable_id", "variant_label", "experiment_id", "frequency", "grid_label", "source_id"]
meta_data = {k: all_attrs[k] for k in keys_to_keep if k in all_attrs}

# The first thing we need to do is get the annual field which should be total
# carbon content per year.
# TODO right now we are assuming a 365 day calander across models we may want to update this.
seconds_per_year = (365 * 24 * 60 * 60) / 12
annual_monthly_rate = d.coarsen(time=12).sum() * seconds_per_year

# Calculate the land cell area, make sure that the land cell area where
# land is 0 assign it a na value so that
land_cell_area = cell_area.areacella * land_percent.sftlf * (1 / 100)
land_cell_area = land_cell_area.where(land_cell_area != 0, other=np.nan)

# Calculate the total annual carbon. Update attributes to reflect the
# new units.
field = annual_monthly_rate * land_cell_area.values


# Convert from kg of C to the Petagram of C which are the
# unites I am used to thinking in/hector units.
field = field * 1e-12


type(field)



field.attrs["frequency"] = "year"
field.attrs["units"] = "Pg C"


# The global values, for the carbon values this is going to be
# the global total, since we have already multiplied by the
# land area we do not need to do the weighting.
other_dims = set(field.dims) - {"time"}
global_ts = field.sum(other_dims, skipna=True)
global_ts.to_netcdf(global_ofile, mode='w')


