# Process carbon data files and train the LPS. This script trains on historical & ssp585
# scenario dataa.

import fxns
import numpy as np
import pandas as pd
import os


# Prep where to write the processed data out to
DATA_DIR = "./exp0/data/"
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(DATA_DIR+"field", exist_ok=True)
os.makedirs(DATA_DIR+"global", exist_ok=True)
os.makedirs(DATA_DIR+"beta", exist_ok=True)
os.makedirs(DATA_DIR+"intercept", exist_ok=True)
os.makedirs(DATA_DIR+"yhat", exist_ok=True)
os.makedirs(DATA_DIR+"error_metrics", exist_ok=True)


# Read in the data frame with the files to process
to_process = pd.read_csv('./npp_rh_to_process.csv')

for index, row in to_process.iterrows():

    data_path = to_process["zstore"][index]

    # Determine the tag name, this is how
    tag = data_path.replace("gs://", "")
    tag = tag.replace("/", "_")
    tag = tag.replace("cmip6_CMIP6_CMIP_", "")
    tag = tag.replace("cmip6_CMIP6_ScenarioMIP_", "")

    # Files that are going to be generated by this script...
    field_ofile = DATA_DIR + "field/" + tag + "field.nc"
    global_ofile = DATA_DIR + "global/" + tag + "global.nc"

    # Load the required netcdf files.
    d = fxns.fetch_nc(data_path)
    cell_area = fxns.fetch_nc(to_process["areacella"][index])
    land_percent = fxns.fetch_nc(to_process["sftlf"][index])

    # Save meta data information
    VAR = d.variable_id
    all_attrs = d.attrs
    original_units = d[VAR].units
    keys_to_keep = ["variable_id", "variant_label", "experiment_id", "frequency", "grid_label", "source_id"]
    meta_data = {k: all_attrs[k] for k in keys_to_keep if k in all_attrs}

    # TODO the processing may change depending on the variable
    if VAR == "tas":
        # The first thing to do is to get the gridded annual mean that will be
        # used in the linear process scaling. Will need to update the frequency.
        # Save a copy of the annual mean values to local disk, this will be used in LPS.
        annual_field = d.coarsen(time=12).mean() - 273.15

        # Let's work on in the temperature anomoly space...
        selected_data = annual_field.sel(time=slice('1850', '1900'))
        ref_temp = selected_data.mean(dim="time")
        field = annual_field - ref_temp
        field.attrs["frequency"] = 'yr'
        field.to_netcdf(field_ofile, mode='w')

        # Now get the global mean value, these global values need to be weighted.
        lat = field[fxns.get_lat_name(field)]
        weight = np.cos(np.deg2rad(lat))
        weight /= weight.mean()
        other_dims = set(d.dims) - {"time"}
        global_ts = (field * weight).mean(other_dims)
        global_ts.to_netcdf(global_ofile, mode='w')
    elif VAR in ["npp", "rh"]:

        # The first thing we need to do is get the annual field which should be total
        # carbon content per year.
        # TODO right now we are assuming a 365 day calander across models we may want to update this.
        seconds_per_year = (365 * 24 * 60 * 60) / 12
        annual_monthly_rate = d.coarsen(time=12).sum() * seconds_per_year

        # Calculate the land cell area, make sure that the land cell area where
        # land is 0 assign it a na value so that
        land_cell_area = cell_area.areacella * land_percent.sftlf * (1 / 100)
        land_cell_area = land_cell_area.where(land_cell_area != 0, other=np.nan)

       # Calculate the total annual carbon. Update attributes to reflect the
        # new units.
        # TODO figure out a way to add the attribtue information!
        field = annual_monthly_rate * land_cell_area.values
        #np.nanmax(field.npp.values)

        # Convert from kg of C to the Petagram of C which are the
        # unites I am used to thinking in/hector units.
        field = field * 1e-12
        #np.nanmax(field.npp.values)

        # annual_total_carbon = annual_total_carbon.assign_attrs()
        # meta_data["frequency"] = "yr"
        # meta_data["units"] = original_units.replace(" m-2 s-1", "")
        # for k, v in meta_data.items():
        #    annual_total_carbon.attrs[f"{k}"] = str(v)
        field.attrs["frequency"] = "year"
        field.attrs["units"] = "Pg C"
        field.to_netcdf(field_ofile, mode="w")

        # The global values, for the carbon values this is going to be
        # the global total, since we have already multiplied by the
        # land area we do not need to do the weighting.
        other_dims = set(field.dims) - {"time"}
        global_ts = field.sum(other_dims, skipna=True)
        global_ts.to_netcdf(global_ofile, mode='w')

    else:
        print("Data processing not implemented")

    # Linear Pattern Scaling Portion
    # The times should align since we are originating from the same raw netcdf file
    # although this is an assumption TODO don't rely on assumptions.
    field_with_global = field.copy()
    field_with_global["time"] = global_ts[VAR]
    field_with_global = field_with_global.rename({VAR: "field"})

    # Use the field with global time series to do the regression.
    # Save the results.
    reg = field_with_global.polyfit(dim="time", deg=1)
    beta = reg.field_polyfit_coefficients.sel(degree=1)
    intercept = reg.field_polyfit_coefficients.sel(degree=0)

    beta.to_netcdf(DATA_DIR + "beta/" + tag + "beta.nc", mode='w')
    intercept.to_netcdf(DATA_DIR + "intercept/" + tag + "intercept.nc", mode='w')

    # Beyond here are extra QAQC steps that will not be part of the formal pipeline.
    # Pattern-scaled reconstruction
    yhat = beta * global_ts + intercept
    yhat = yhat.transpose(*("lat", "lon", "time"))
    yhat.to_netcdf(DATA_DIR + "yhat/" + tag + "yhat.nc", mode='w')

    # Error metrics for quailty checks, these are going to tbe the most standardized versions.
    # TODO this following chunk is part of the QAQC and will probably be removed from the formal pipeline
    # TODO might want to consider masking out the 0s so that we don't run into issues with NAs, although
    # that might be overkil...
    # These are all our "insample" error metrics
    var_obs = field.var(dim="time")
    sd_obs = var_obs ** 0.5
    sd_sim = yhat.var(dim="time") ** 0.5
    mean_obs = field.mean(dim="time")
    mean_sim = yhat.mean(dim="time")

    resid = yhat - field
    mse = (resid * resid).mean(dim="time")
    ns = mse / var_obs
    ct_bias = abs(mean_obs - mean_sim) / sd_obs
    ct_var = sd_sim / sd_obs

    resid.to_netcdf(DATA_DIR + "error_metrics/" + tag + "resid.nc", mode='w')
    mse.to_netcdf(DATA_DIR + "error_metrics/" + tag + "mse.nc", mode='w')
    ns.to_netcdf(DATA_DIR + "error_metrics/" + tag + "ns.nc", mode='w')
    ct_bias.to_netcdf(DATA_DIR + "error_metrics/" + tag + "ctbias.nc", mode='w')
    ct_var.to_netcdf(DATA_DIR + "error_metrics/" + tag + "ctvar.nc", mode='w')
