# The purpose of this script is to make a mask that will be used to filter out the low values
# for the fluxes that we think are giving us issues...

# 0. Set Up ------------------------------------------------------------------------------------------------------------
import fxns
import numpy as np
import pandas as pd
import os
import xarray as xr


# Prep where to write the processed data out to
DATA_DIR = "./exp2/data/"
os.makedirs(DATA_DIR+"mask", exist_ok=True)

# Define the percentile to mask out.
th = 50

# Read in the data frame with the files to process, we can
# either pull directly from the online archive or
# from the locally loaded versions.
LOCAL = True

# 1. Main Chunk ------------------------------------------------------------------------------------------------------------
if LOCAL:
    to_process = pd.read_csv('./local_npp_rh_to_process.csv')
else:
    to_process = pd.read_csv('./npp_rh_to_process.csv')

# we are going to assume that history is representiavie of the regions where the low productivity
# are constant over time.
to_process = to_process[to_process["zstore"].str.contains("historical", na=False)]

# For each of the historical files let's create a mask where there is low producvitiy,
# I am also curious to see if/how this changes with the ensemble realizations.
for index, row in to_process.iterrows():

    data_path = to_process["zstore"][index]

    # Determine the tag name
    tag = data_path.replace("gs://", "")
    tag = tag.replace("/", "_")
    tag = tag.replace("cmip6_CMIP6_CMIP_", "")
    tag = tag.replace("cmip6_CMIP6_ScenarioMIP_", "")

    if LOCAL:
        tag = tag.replace("._raw-data_data_", "")
        tag = tag.replace(".nc", "")

    # Load the required netcdf files.
    if LOCAL:
        d = xr.open_dataset(data_path)
        cell_area = xr.open_dataset(to_process["areacella"][index])
        land_percent = xr.open_dataset(to_process["sftlf"][index])
    else:
        d = fxns.fetch_nc(data_path)
        cell_area = fxns.fetch_nc(to_process["areacella"][index])
        land_percent = fxns.fetch_nc(to_process["sftlf"][index])

    VAR = d.variable_id

    if VAR in ["npp", "rh"]:

        # The first thing we need to do is get the annual field which should be total
        # carbon content per year.
        # TODO right now we are assuming a 365 day calander across models we may want to update this.
        seconds_per_year = (365 * 24 * 60 * 60) / 12
        annual_monthly_rate = d.coarsen(time=12).sum() * seconds_per_year

        # Calculate the land cell area, make sure that the land cell area where
        # land is 0 assign it a na value so that
        land_cell_area = cell_area.areacella * land_percent.sftlf * (1 / 100)
        land_cell_area = land_cell_area.where(land_cell_area != 0, other=np.nan)

       # Calculate the total annual carbon. Update attributes to reflect the
       # new units.
        field = annual_monthly_rate * land_cell_area.values

        # Convert from kg of C to the Petagram of C which are the
        # unites I am used to thinking in/hector units.
        field = field * 1e-12

        # EXP2 CODE - experiment specific code, exclude the gridcells that have low or essentially 0
        # carbon fluxes. Note that this cut off is somewhat arbitraty.
        # Now average again over time, so now we are looking at the historical average
        hist_mean = field.mean("time")

        # EXP2 CODE - experiment specific code, exclude the gridcells that have low or essentially 0
        # carbon fluxes. Note that this cut off is somewhat arbitraty.
        # TODO could possibly consider instead of writing as na maybe change to 0s?
        percentile_th = np.nanpercentile(abs(hist_mean[VAR].values), th)

        hist_mean[VAR] = hist_mean[VAR].where(hist_mean[VAR] >= percentile_th)
        mask = xr.where(hist_mean[VAR] > percentile_th, 1, np.nan)

        mask.attrs['notes'] = "mask out the values < " + str(th) + " percentaile"
        mask.attrs["units"] = "boolean"

        # Files that are going to be generated by this script...
        mask_ofile = DATA_DIR + "mask/" + tag + "mask_" + str(th) + ".nc"

        mask.to_netcdf(mask_ofile, mode='w')